neurospin/pypreprocess

pypreprocess/nipype_preproc_spm_utils.py

BF: (issue #85) delt with troublesome cv_tc param in dartel stuff

---

README.rst
examples/nipy_glm_fsl_feeds_fmri.py
examples/nipype_preproc_spm_nyu.py

- more cleanups
- more doc
- more

Pretreat 2015

---

pypreprocess/nipype_preproc_spm_utils.py

DARTELNorm2MNIInputSpec - Voxel size as tuple

---

README.rst

Added  && to broken installation instructions.

BF: fixing installation instructions

---

examples/nipype_preproc_spm_multimodal_faces.py
pypreprocess/_spike/pipeline_comparisons.py
pypreprocess/affine_transformations.py
pypreprocess/conf_parser.py
pypreprocess/datasets.py
pypreprocess/external/tempita/__init__.py
pypreprocess/fsl_to_nipy.py
pypreprocess/glm_utils.py
pypreprocess/io_utils.py
pypreprocess/nipype_preproc_spm_utils.py
pypreprocess/purepython_preproc_utils.py
pypreprocess/realign.py
pypreprocess/reporting/base_reporter.py
pypreprocess/reporting/check_preprocessing.py
pypreprocess/reporting/css/styles.css
pypreprocess/reporting/glm_reporter.py
pypreprocess/reporting/preproc_reporter.py
pypreprocess/reporting/template_reports/subject_report_preproc_template.tmpl.html
pypreprocess/reporting/template_reports/subject_report_stats_template.tmpl.html
pypreprocess/reslice.py
pypreprocess/slice_timing.py
pypreprocess/spm_loader/utils.py
pypreprocess/subject_data.py
pypreprocess/tests/_test_utils.py
pypreprocess/tests/test_io_utils.py
pypreprocess/tests/test_kernel_smooth.py
pypreprocess/tests/test_realign.py
pypreprocess/tests/test_reslice.py
pypreprocess/tests/test_slice_timing.py
pypreprocess/tests/test_subject_data.py

Trying to make the report pages as comprehensive as possible to the front-end user.

Tooltips for thumbnails in report pages

---

.travis.yml
examples/purepython_preproc_demo.py
examples/realign_demos.py
pypreprocess/affine_transformations.py
pypreprocess/io_utils.py
pypreprocess/nipype_preproc_spm_utils.py
pypreprocess/purepython_preproc_utils.py
pypreprocess/realign.py
pypreprocess/reporting/check_preprocessing.py
pypreprocess/reslice.py
pypreprocess/slice_timing.py
pypreprocess/subject_data.py
pypreprocess/tests/test_affine_transformations.py
pypreprocess/tests/test_io_utils.py
pypreprocess/tests/test_realign.py
pypreprocess/tests/test_reslice.py
pypreprocess/tests/test_slice_timing.py

- Loading of images is henceforth delegated to nilearn
- Removed dependency on check_niimgs
- Fixes issue  #106
- etc.

Cleanup purepython code + delegating io to nilearn

---

Makefile
pypreprocess/nipype_preproc_spm_utils.py
pypreprocess/realign.py
pypreprocess/tests/test_coreg.py
pypreprocess/tests/test_realign.py
spike/glm_utils.py

Cleanup nosetests

---

pypreprocess/nipype_preproc_spm_utils.py

BF: issue #115

---

pypreprocess/configure_spm.py
pypreprocess/nipype_preproc_spm_utils.py
pypreprocess/reporting/preproc_reporter.py

Just added a function to check SPM version then the templates paths are set according to the version.

Spm12 support

---

pypreprocess/configure_spm.py
pypreprocess/nipype_preproc_spm_utils.py
pypreprocess/reporting/preproc_reporter.py

Reverts neurospin/pypreprocess#134

Revert "Spm12 support"

---

pypreprocess/reporting/check_preprocessing.py

I don't know why it is set to False...

Set black_bg to True in plot_segmentation

---

examples/pure_python/slice_timing_demos.py
pypreprocess/reporting/glm_reporter.py

* broken imports in examples
* bug prior to reorder_img call

Various issues

---

examples/pure_python/realign_demos.py

Replacing the import from pypreprocess with the import from nilearn.
The example was not working.

Fix import nyu dataset

---

pypreprocess/subject_data.py

BF: Removing spaces in output image names

---

setup.py

externals/nistats missing in setup.py

fixing broken nistats integration

---

README.rst

Add circleCI badge

---

pypreprocess/conf_parser.py
pypreprocess/tests/test_conf_parser.py

Fixes issue #181

---

README.rst

Describing this step is essential, I guess before starting to run examples.
Let me know how it goes ?

Fixing documentation issue "Failure to configure SPM on own device"

---

examples/easy_start/spm_auditory_preproc.ini

We want this example to be as light as possible.

disabling newsegment in auditory example (senseless)

---

pypreprocess/tests/test_tsdiffana.py
pypreprocess/time_diff.py

Taking care of Nans in tsdiffana

---

pypreprocess/tests/test_version.py
pypreprocess/version.py

All is in title.
For more, refer Issue #133

Test added to make sure "__version__" exists in pypreprocess

---

README.rst

Recommend pip install instead sudo apt-get  for the python packages

update README.rst for install

---

examples/pure_python/coreg_demos.py

- fetcher is now imported from nilearn

Fixing broken example: failure fetch_nyu_rest

---

Makefile
pypreprocess/external/nistats/utils.py
pypreprocess/external/tempita/__init__.py
pypreprocess/reporting/glm_reporter.py

Fixes issue #219. Cleaning Makefile (removing test cases: test-doc, doc-noplot, etc.

CLEANUP: cleaning Makefile. Fixes issue #219

---

pypreprocess/nipype_preproc_spm_utils.py
pypreprocess/subject_data.py

Fix NewSegment links in subject_data

---

examples/easy_start/nipype_preproc_spm_auditory.py

FIX: position-indpendences in example code (fixes issue #178)

---

examples/easy_start/nipype_preproc_spm_auditory.py
examples/pipelining/nipype_preproc_spm_multimodal_faces.py
examples/pipelining/nistats_glm_fsl_feeds_fmri.py
pypreprocess/conf_parser.py
pypreprocess/external/nistats/design_matrix.py
pypreprocess/external/nistats/experimental_paradigm.py
pypreprocess/external/nistats/glm.py
pypreprocess/external/nistats/hemodynamic_models.py
pypreprocess/external/nistats/regression.py
pypreprocess/external/nistats/utils.py
pypreprocess/reporting/glm_reporter.py
pypreprocess/spm_loader/utils.py
scripts/hcp_preproc_and_analysis.py
scripts/openfmri.py
spike/sprint.py

Upgraded nistats to solve growing incompatibilities between nistats master and pypreprocess.
Note: more to come due to nistats refactoring.

[MRG] Nistat upgrade

---

pypreprocess/slice_timing.py
pypreprocess/tests/test_slice_timing.py

FIX: fixes issue #232 on slice indices for STC

---

pypreprocess/io_utils.py

BF: fixes issue #236

---

pypreprocess/subject_data.py

BF: fixing indexation bug introduced by PR #230

BF: fixing indexation bug introduced by PR #230

---

pypreprocess/io_utils.py
pypreprocess/tests/test_io_utils.py

Use get_header to access nibabel headers.

---

examples/easy_start/nipype_preproc_spm_auditory.py
examples/easy_start/segmentation_demos.py
pypreprocess/reporting/check_preprocessing.py

Fix pyplot import in circleci

---

pypreprocess/realign.py
pypreprocess/slice_timing.py

Cast indices to ints so numpy would not complain.

---

README.rst

Update the install information to use `scikit-learn` and not the alias `sklearn`

[MRG] FIX installation in README

---

pypreprocess/nipype_preproc_spm_utils.py

We don't want everything to crash if there is a fault while processing some subject. We want to keep going, and perhaps report failures in the very end.

ENH: fault-tolerance via ignore_exception=True

---

pypreprocess/realign.py
pypreprocess/tests/test_realign.py

If anyone knows how to achieve this parallelization while avoiding serializing data on disk that would speed things even more.

Added ability to perform realignment in parallel (across volumes).

---

.travis.yml
continuous_integration/install.sh

(mainly due to bad nipype / nilearn / scipy version numbers)

BF: fixing broken travis build matrix 

---

examples/pipelining/nipype_preproc_spm_multimodal_faces.py
examples/pipelining/nistats_glm_fsl_feeds_fmri.py
examples/pure_python/realign_demos.py
examples/pure_python/slice_timing_demos.py
scripts/hcp_preproc_and_analysis.py
spike/sprint.py

Although the majority of python 3 related changes were addressed in #266 , there were still some xrange lingering around that made some examples not work in python 3

changed xrange for range

---

.travis.yml
continuous_integration/install.sh
pypreprocess/coreg.py
pypreprocess/nipype_preproc_spm_utils.py
pypreprocess/tests/test_slice_timing.py

Travis build completes again. Circle CI build fails due to an SPM-related permission error. Looking into it now.

Circleci fix

---

.circleci/config.yml
examples/easy_start/nipype_preproc_spm_auditory.py
examples/pipelining/nipype_preproc_spm_multimodal_faces.py
examples/pipelining/nistats_glm_fsl_feeds_fmri.py
pypreprocess/reporting/glm_reporter.py
pypreprocess/reporting/preproc_reporter.py

@bthirion CircleCI passes! I updated the nistats references in the examples run by CircleCI to use the nilearn.stats functions instead, and circleci now passes. It's time nistats was merged into nilearn! :~) 
This PR doesn't have to be merged as is, I created it more for proof-of-concept; there is some ugly commenting of code in the examples that should be removed before merging.

Nistats update

---

README.rst
examples/easy_start/nipype_preproc_spm_auditory.py
examples/pipelining/nipype_preproc_spm_multimodal_faces.py
examples/pipelining/nistats_glm_fsl_feeds_fmri.py
pypreprocess/datasets.py
pypreprocess/nipype_preproc_spm_utils.py

I've tested the installation instructions on Ubuntu 16 w/ Python 3.6 and Ubuntu 18 w/ Python 3.6. Works.

Updated installation instructions
